mixed-port: 10808
allow-lan: false
external-controller: 127.0.0.1:11208
secret: 123456
log-level: debug

proxy-providers:
  #All
  All:
    type: http
    # your url
    url: ""
    path: e:/clash/proxies/miru.yml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  #é¦™æ¸¯èŠ‚ç‚¹
  HK:
    type: file
    path: e:/clash/proxies/miru.yml
    filter: æ¸¯|HK|(?i)Hong
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204
  #æ—¥æœ¬èŠ‚ç‚¹
  JP:
    type: file
    path: e:/clash/proxies/miru.yml
    filter: æ—¥|ä¸œäº¬|JP|(?i)Japan
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204
  #ç¾å›½èŠ‚ç‚¹
  US:
    type: file
    path: e:/clash/proxies/miru.yml
    filter: ç¾|US|(?i)States|American
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204
  #å°æ¹¾èŠ‚ç‚¹
  TW:
    type: file
    path: e:/clash/proxies/miru.yml
    filter: å°|æ¹¾|TW|(?i)Taiwan
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204
  #æå®¶å¡èŠ‚ç‚¹
  SG:
    type: file
    path: e:/clash/proxies/miru.yml
    filter: æ–°|å¡|SG|(?i)Singapore
    health-check:
      enable: true
      interval: 120
      url: http://www.gstatic.com/generate_204

proxies:

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.4.4
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
    - https://dns.google/dns-query

proxy-groups:
  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯è½¬ç§»
      - ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªé€‰
      - ğŸ‡¨ğŸ‡³ å°æ¹¾è½¬ç§»
      - ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªé€‰
      - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è‡ªé€‰
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªé€‰
      - ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªé€‰
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯è‡ªé€‰
    type: url-test
    use:
      - HK
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯è½¬ç§»
    type: fallback
    use:
      - HK
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾è‡ªé€‰
    type: url-test
    use:
      - TW
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾è½¬ç§»
    type: fallback
    use:
      - TW
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡è‡ªé€‰
    type: url-test
    use:
      - SG
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬è‡ªé€‰
    type: url-test
    use:
      - JP
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½è‡ªé€‰
    type: url-test
    use:
      - US
    url: "http://www.gstatic.com/generate_204"
    interval: 300
  - name: âœˆï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    use:
      - All
    url: "http://www.gstatic.com/generate_204"
    interval: 300

  - name: ğŸ¬ YouTube
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - DIRECT

  - name: ğŸ¬ NETFLIX
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - DIRECT

  - name: ğŸ¬ Disney+
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - DIRECT

  - name: ğŸ¬ å·´å“ˆå§†ç‰¹
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - DIRECT

  - name: ğŸ† AdBlock
    type: select
    proxies:
      - REJECT
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢

  - name: ğŸŒ å›½å¤–ç½‘ç«™
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - DIRECT

  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹

  - name: ğŸ§© å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - DIRECT
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹

  - name: ğŸ¶ ç½‘æ˜“éŸ³ä¹
    type: select
    proxies:
      - DIRECT

  - name: ğŸ¬ å“”å“©å“”å“©
    type: select
    proxies:
      - DIRECT
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹

  - name: ğŸ® æ¸¸æˆå¹³å°
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹

  - name: ğŸŒ å›½å†…ç½‘ç«™
    type: select
    proxies:
      - DIRECT
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹

  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
      - DIRECT
      - âœˆï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: select
    use:
      - HK
    proxies:
      - DIRECT
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: select
    use:
      - JP
    proxies:
      - DIRECT
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    type: select
    use:
      - TW
    proxies:
      - DIRECT
  - name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
    type: select
    use:
      - US
    proxies:
      - DIRECT

rule-providers:
  # Direct:
  #   type: http
  #   behavior: classical
  #   url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml"
  #   path: ./ruleset/direct.yaml
  #   interval: 86400

  adblock:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising_Classical.yaml"
    path: ./ruleset/Advertising_Classical.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml"
    path: ./ruleset/Netflix.yaml
    interval: 86400

  Disney:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml"
    path: ./ruleset/Disney.yaml
    interval: 86400

  Bahamut:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Bahamut/Bahamut.yaml"
    path: ./ruleset/Bahamut.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml"
    path: ./ruleset/Apple.yaml
    interval: 86400

  NetEaseMusic:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml"
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  BiliBili:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  Game:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.yaml"
    path: ./ruleset/Game.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/China/China.yaml"
    path: ./ruleset/China.yaml
    interval: 86400

  Global_Classical:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@release/rule/Clash/Global/Global_Classical.yaml"
    path: ./ruleset/Global_Classical.yaml
    interval: 86400

rules:
  # - RULE-SET,Direct,DIRECT
  - RULE-SET,adblock,ğŸ† AdBlock
  - RULE-SET,YouTube,ğŸ¬ YouTube
  - RULE-SET,Netflix,ğŸ¬ NETFLIX
  - RULE-SET,Disney,ğŸ¬ Disney+
  - RULE-SET,Bahamut,ğŸ¬ å·´å“ˆå§†ç‰¹
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Microsoft,ğŸ§© å¾®è½¯æœåŠ¡
  - RULE-SET,NetEaseMusic,ğŸ¶ ç½‘æ˜“éŸ³ä¹
  - RULE-SET,BiliBili,ğŸ¬ å“”å“©å“”å“©
  - RULE-SET,Game,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Global_Classical,ğŸŒ å›½å¤–ç½‘ç«™
  - RULE-SET,China,ğŸŒ å›½å†…ç½‘ç«™
  - DOMAIN,ad.10010.com,DIRECT
  - DOMAIN,alt1-mtalk.google.com,DIRECT
  - DOMAIN,alt2-mtalk.google.com,DIRECT
  - DOMAIN,alt3-mtalk.google.com,DIRECT
  - DOMAIN,alt4-mtalk.google.com,DIRECT
  - DOMAIN,alt5-mtalk.google.com,DIRECT
  - DOMAIN,alt6-mtalk.google.com,DIRECT
  - DOMAIN,alt7-mtalk.google.com,DIRECT
  - DOMAIN,alt8-mtalk.google.com,DIRECT
  - DOMAIN,analytics.95516.com,DIRECT
  - DOMAIN,analytics.strava.com,DIRECT
  - DOMAIN,app.adjust.com,DIRECT
  - DOMAIN,app.appsflyer.com,DIRECT
  - DOMAIN,bdtj.tagtic.cn
  - DOMAIN,clientservices.googleapis.com,DIRECT
  - DOMAIN,dl.google.com,DIRECT
  - DOMAIN,dl.l.google.com,DIRECT
  - DOMAIN,eco-push-api-client.meiqia.com,DIRECT
  - DOMAIN,errlog.umeng.com,DIRECT
  - DOMAIN,fairplay.l.qq.com,DIRECT
  - DOMAIN,fonts.googleapis.com,DIRECT
  - DOMAIN,fonts.gstatic.com,DIRECT
  - DOMAIN,livew.l.qq.com,DIRECT
  - DOMAIN,log.mmstat.com,DIRECT
  - DOMAIN,msg.umeng.com,DIRECT
  - DOMAIN,msg.umengcloud.com,DIRECT
  - DOMAIN,mtalk.google.com,DIRECT
  - DOMAIN,new-api.meiqia.com,DIRECT
  - DOMAIN,origin-a.akamaihd.net,DIRECT
  - DOMAIN,picanalysis-auth.vivo.com.cn,DIRECT
  - DOMAIN,picanalysis.vivo.com.cn,DIRECT
  - DOMAIN,rewards.hypixel.net,DIRECT
  - DOMAIN,sycm.mmstat.com,DIRECT
  - DOMAIN,tracking.miui.com,DIRECT
  - DOMAIN,update.googleapis.com,DIRECT
  - DOMAIN,vd.l.qq.com,DIRECT
  - DOMAIN,vi.l.qq.com,DIRECT
  - DOMAIN,xivanalysis.com,DIRECT
  - DOMAIN-SUFFIX,baomitu.com,DIRECT
  - DOMAIN-SUFFIX,blog.google,DIRECT
  - DOMAIN-SUFFIX,bootcss.com,DIRECT
  - DOMAIN-SUFFIX,dizhensubao.getui.com,DIRECT
  - DOMAIN-SUFFIX,f.video.weibocdn.com,DIRECT
  - DOMAIN-SUFFIX,fus.cdn.krcom.cn,DIRECT
  - DOMAIN-SUFFIX,googletraveladservices.com,DIRECT
  - DOMAIN-SUFFIX,jiasule.com,DIRECT
  - DOMAIN-SUFFIX,ol.epicgames.com,DIRECT
  - DOMAIN-SUFFIX,staticfile.org,DIRECT
  - DOMAIN-SUFFIX,tracking-protection.cdn.mozilla.net,DIRECT
  - DOMAIN-SUFFIX,upaiyun.com,DIRECT
  - DOMAIN-KEYWORD,wb_ad,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,fe80::/10,DIRECT
  - IP-CIDR,119.28.28.28/32,DIRECT
  - IP-CIDR,182.254.116.0/24,DIRECT
  - GEOIP,CN,ğŸŒ å›½å†…ç½‘ç«™
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
  - DOMAIN-SUFFIX,gitee.com,DIRECT
